// vue3-admin/src/views/Login.vue
<script setup>
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getDemoAccounts, login } from '../services/auth'

const route = useRoute()
const router = useRouter()
const form = ref({ username: '', password: '' })
const error = ref('')
const loading = ref(false)
const demoAccounts = getDemoAccounts()

const submit = async () => {
  error.value = ''
  loading.value = true
  try {
    await login(form.value.username, form.value.password)
    const redirect = route.query.redirect || '/dashboard'
    router.push(redirect)
  } catch (err) {
    error.value = 'Invalid credentials. Try a demo account below.'
  } finally {
    loading.value = false
  }
}

const fillDemo = (account) => {
  form.value.username = account.username
  form.value.password = account.password
}
</script>

<template>
  <section class="login">
    <div class="card login-card">
      <div class="card-title">Sign in</div>
      <p class="page-description">
        This login page enables permission control. Session tokens persist and
        refresh automatically for protected requests.
      </p>
      <form class="login-form" @submit.prevent="submit">
        <label class="field">
          <span class="field-label">Username</span>
          <input v-model="form.username" class="input" type="text" />
        </label>
        <label class="field">
          <span class="field-label">Password</span>
          <input v-model="form.password" class="input" type="password" />
        </label>
        <button class="ghost-button" type="submit" :disabled="loading">
          {{ loading ? 'Signing in...' : 'Sign in' }}
        </button>
        <p v-if="error" class="error">{{ error }}</p>
      </form>

      <div class="demo">
        <div class="demo-title">Demo accounts</div>
        <div class="demo-actions">
          <button
            v-for="account in demoAccounts"
            :key="account.username"
            class="secondary-button"
            type="button"
            @click="fillDemo(account)"
          >
            {{ account.username }} ({{ account.role }})
          </button>
        </div>
      </div>
    </div>
  </section>
</template>

// react-admin/src/pages/Login.jsx
import { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { getDemoAccounts } from '../auth/auth'

function Login() {
  const { login } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const from = location.state?.from?.pathname || '/dashboard'
  const [form, setForm] = useState({ username: '', password: '' })
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const demoAccounts = getDemoAccounts()

  const handleSubmit = async (event) => {
    event.preventDefault()
    setError('')
    setLoading(true)
    try {
      await login(form.username, form.password)
      navigate(from, { replace: true })
    } catch (err) {
      setError('Invalid credentials. Try a demo account below.')
    } finally {
      setLoading(false)
    }
  }

  const fillDemo = (account) => {
    setForm({ username: account.username, password: account.password })
  }

  return (
    <div className="auth-layout">
      <section className="login">
        <div className="card login-card">
          <div className="card-title">Sign in</div>
          <p className="page-description">
            This login page enables permission control. Session tokens persist
            and refresh automatically for protected requests.
          </p>
          <form className="login-form" onSubmit={handleSubmit}>
            <label className="field">
              <span className="field-label">Username</span>
              <input
                className="input"
                type="text"
                value={form.username}
                onChange={(event) =>
                  setForm((prev) => ({ ...prev, username: event.target.value }))
                }
              />
            </label>
            <label className="field">
              <span className="field-label">Password</span>
              <input
                className="input"
                type="password"
                value={form.password}
                onChange={(event) =>
                  setForm((prev) => ({ ...prev, password: event.target.value }))
                }
              />
            </label>
            <button className="ghost-button" type="submit" disabled={loading}>
              {loading ? 'Signing in...' : 'Sign in'}
            </button>
            {error ? <p className="error">{error}</p> : null}
          </form>

          <div className="demo">
            <div className="demo-title">Demo accounts</div>
            <div className="demo-actions">
              {demoAccounts.map((account) => (
                <button
                  key={account.username}
                  type="button"
                  className="secondary-button"
                  onClick={() => fillDemo(account)}
                >
                  {account.username} ({account.role})
                </button>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Login
