// vue3-admin/src/components/NotificationPanel.vue
<script setup>
const props = defineProps({
  notifications: {
    type: Array,
    default: () => []
  },
  unreadCount: {
    type: Number,
    default: 0
  }
})

const emit = defineEmits(['close', 'markRead', 'markAll'])
</script>

<template>
  <div class="notification-panel">
    <div class="notification-header">
      <div>
        <div class="card-title">Notifications</div>
        <div class="card-subtitle">
          Updated through the mock WebSocket feed.
        </div>
      </div>
      <button class="secondary-button" type="button" @click="emit('close')">
        Close
      </button>
    </div>
    <div class="notification-actions">
      <span>{{ unreadCount }} unread</span>
      <button class="ghost-button" type="button" @click="emit('markAll')">
        Mark all read
      </button>
    </div>
    <div class="notification-list">
      <div
        v-for="note in notifications"
        :key="note.id"
        class="notification-item"
        :class="{ unread: !note.read }"
      >
        <div>
          <div class="notification-title">{{ note.title }}</div>
          <div class="notification-body">{{ note.body }}</div>
          <div class="notification-time">{{ note.time }}</div>
        </div>
        <button
          class="secondary-button"
          type="button"
          @click="emit('markRead', note.id)"
        >
          Mark read
        </button>
      </div>
    </div>
  </div>
</template>

// react-admin/src/components/NotificationPanel.jsx
function NotificationPanel({
  notifications,
  unreadCount,
  onClose,
  onMarkRead,
  onMarkAll,
}) {
  return (
    <div className="notification-panel">
      <div className="notification-header">
        <div>
          <div className="card-title">Notifications</div>
          <div className="card-subtitle">
            Updated through the mock WebSocket feed.
          </div>
        </div>
        <button className="secondary-button" type="button" onClick={onClose}>
          Close
        </button>
      </div>
      <div className="notification-actions">
        <span>{unreadCount} unread</span>
        <button className="ghost-button" type="button" onClick={onMarkAll}>
          Mark all read
        </button>
      </div>
      <div className="notification-list">
        {notifications.map((note) => (
          <div
            key={note.id}
            className={`notification-item${note.read ? '' : ' unread'}`}
          >
            <div>
              <div className="notification-title">{note.title}</div>
              <div className="notification-body">{note.body}</div>
              <div className="notification-time">{note.time}</div>
            </div>
            <button
              className="secondary-button"
              type="button"
              onClick={() => onMarkRead(note.id)}
            >
              Mark read
            </button>
          </div>
        ))}
      </div>
    </div>
  )
}

export default NotificationPanel
